#!/usr/bin/env sh
xset -dpms
xset s off
xset s noblank

unclutter &
pm2 start ~/display/server/index.js &
chromium-browser http://localhost:8080/ \
  --window-size=480,1920 \
  --window-position=0,0 \
  --start-fullscreen \
  --kiosk \
  --incognito \
  --noerrdialogs \
  --disable-translate \
  --no-first-run \
  --fast \
  --fast-start \
  --disable-infobars \
  --disable-features=TranslateUI \
  --disk-cache-dir=/dev/null \
  --overscroll-history-navigation=0 \
  --disable-pinch
